---

- name: "Rust | Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 600
  changed_when: false

- name: "Rust | Install dependencies"
  apt:
    name:
      - curl
      - gcc
    state: present