---

- name: "Rust | Update apt cache"
    apt:
      update_cache: yes
      cache_valid_time: 600

- name: "Rust | Install dependencies"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl
    - gcc